version: "3.5"
services:
  php_fpm:
    image: brunoba93/php_fpm_laravel
    container_name: php_fpm
    working_dir: /usr/share/nginx/scheduler
    networks:
      - backend
    volumes:
      - ./:/usr/share/nginx/scheduler
  nginx:
    image: nginx:1.15
    container_name: nginx
    working_dir: /usr/share/nginx/scheduler
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./:/usr/share/nginx/scheduler
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=scheduler
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=brunoba
      - MYSQL_PASSWORD=password
  mysql_test:
    image: mysql:5.7
    container_name: mysql_test
    ports:
      - "3307:3306"
    expose:
      - 3306
      - 3307
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=scheduler_test
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=brunoba
      - MYSQL_PASSWORD=password
networks:
  backend:
    driver: bridge
